### ISSUE TITLE
Issue Load_dataset

### ISSUE THREAD

**Issue by d29122019** [DQSSSSS/VectorNet#1]
in function load_data in run_All_Test.py, I cannot load the dataset:
The dataset xxxxx.csv in formatted in this way [TIMESTAMP,TRACK_ID,OBJECT_TYPE,X,Y,CITY_NAME]  , but the code use some index like polyline_ID = 8 that are out of bounds. When I  run python3 run_All_Test.py I got this error:
Traceback (most recent call last):
  File "run_All_Test.py", line 149, in <module>
    test = load_data(root_dir, TEST_FILE[it:maxJ])
  File "run_All_Test.py", line 42, in load_data
    ans[i, polyline_ID] != ans[i + 1, polyline_ID]:
IndexError: index 8 is out of bounds for axis 1 with size 6

How can I fix this?, maybe I made a mistake about the root path ?
Thanks

**Comment by DQSSSSS** [comment]
Oh! Because Argoverse dataset's API must run on Ubuntu/MacOS and I coded on Windows, I used a very silly method to tackle the  loading of dataset. I pre-processed the dataset on WSL(Windows Subsystem for Linux) and then trained model on Windows.
The reason is that coding on WSL is so uncomfortable, and I don't have Linux environment. You also can do the same work to pre-process dataset.
If you can use Argoverse dataset's API conveniently, please take some time to explore the document or/and source code of API, you will find some great function to help you deal with data.
For my code, I just uploaded '2.py', function 'work' is all you need! In short, 'work' formatted data as '[start_X, start_Y, end_X, end_Y, type, att1, att2, att3, polyline_id]' and do some padding, regularization and centralization etc.

**Comment by d29122019** [comment]
Thank you, as you suggested the problem is fixed (I remoed exit(0) at line88 in 2.py, so I generated the entire dataset) , but now I got an assertion fail:
  File "run_All_Test.py", line 150, in <module>
    test = load_data(root_dir, TEST_FILE[it:maxJ])
  File "run_All_Test.py", line 51, in load_data
    assert i - j + 1 == 19

**Comment by DQSSSSS** [comment]
Argoverse's test datasets and train/val datasets have different format, predicted agent in test datasets only have trajectory in first 2s, and others have first 5s, so we should divide the latter(make them 2s+3s, for training and testing respectively). Please follow this to change code.
